### ISSUE TITLE
Tool uses only up to 90% of vram when more is available

### ISSUE THREAD

**Issue by TheK0tYaRa** [GpuZelenograd/memtest_vulkan#31]
Can it be used for full memory range tests?

I have an assumption that my rx5700 fails on full load for some reason. Either vbios has incorrect vram size set or there is a faulty chip. Either way the amdgpu driver times out ring_gfx.

**Comment by galkinvv** [comment]
Tool uses only 90% of memory since trying to use more typically just leads to UI lockup.
However this is not a problem most of the times: from practice most of the times memory errors are caused during transmission time, not during storage time. So testing 100%, 90% or even 20% actually gives nearly identical load on the GPU & memory susbsystem.

If you suppose that you have a problem that appears only with higher then 90% memory load - ypu can try specifying the size manually from command line (in bytes, it will be autorounded to a usablevalue):
```
./memtest_vulkan 0 7500000000
```
(and slowly increase the value in last argument).
However be ready that some higher values can lead to "Failed allocating memory" errors or to UI lockup.

Also, GPU hangs can be related to the GPU chip itself, not memory. Or if it appears only when memory is nearly full - just to sotware bugs since this case is less tested.

So, from memtesst_vulkan point of view - this is not bug, but a design decision.

**Comment by TheK0tYaRa** [comment]
Noted, thanks for the information.
